language: java
before_install: git clone http://github.com/revolutionarysystems/travis.git target/travis
script: mvn deploy --settings target/travis/settings.xml
env:
  secure: Hp0xcHbWeoaCjNJyuN2pLeuw6r2xqsHvIUx+3QbpVFEkwwPxY5FcbNZur1AT/NE6Fy1E9Y+qq6HBMzbC6T5ae/j4vstYKlJNRaELDmxeUdayQTNSpN2d9fssqG6SG/KHYXD0vT4yR1ve6341XrAi/twt+lNr42JTBou0Xs2ldpI=
